version: "3"

services:
  server:
    image: ghcr.io/kyosakuyo/microblog.pub:v2
    container_name: microblogpub
    user: root:root
    restart: always
    volumes:
      - ./data:/app/data
      - ./app/static:/app/app/static
    ports:
      - "8000:8082"
